import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Layout } from "../../features/Layout";
import {
  useCastVote,
  useCastVotePaymaster,
  useCastVotePaymaster2,
} from "src/hooks/useCreateProposal";

const Welcome: NextPage = () => {
  const router = useRouter();

  const mockData = {
    id: 2,
    title: "Voting 2",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget aliquam quam. Donec euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae aliquam nisl nunc eu nisl. Donec euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae aliquam nisl nunc eu nisl.",
    status: "active",
  };
  const { votingId } = router.query;

  // Create a function to use useCastVote hook to vote yes/no
  const castVote = useCastVotePaymaster2();

  // get the proposalId from the url

  const voteYes = () => {
    castVote.mutate({
      proposalId: "",
      vote: 1, //
    });
  };

  return (
    <>
      <Head>
        <title>{mockData.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container flex w-full gap-12 px-4 py-16 ">
          <div className="flex w-2/3 flex-col">
            <h2>
              Subject: {mockData.title}
              ID: {votingId}
            </h2>
            <div className="badge-secondary badge">
              status: {mockData.status}
            </div>
            <p className="">{mockData.description}</p>
            <div className="flex flex-col">
              <p>History:</p>
              <p>A voted</p>
              <p>B voted</p>
              <p>C voted</p>
              <p>D voted</p>
            </div>
          </div>
          <div className="flex w-1/3 flex-col">
            Please vote yes / no below. Voting ends in 15d, 12h, 32m
            <p>Total participants: 12</p>
            <p>Total votes: 8</p>
            Yes: 5 No: 3
            <div className="flex ">
              <button
                className="mx-15 btn-accent btn"
                onClick={() =>
                  castVote.mutate({
                    proposalId: votingId as string,
                    vote: 1, //
                  })
                }
              >
                Yes
              </button>
              <button className="btn-secondary btn py-10">No</button>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Welcome;
