/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../common";

export type ImmutableDataStruct = { index: BigNumberish; value: BytesLike };

export type ImmutableDataStructOutput = [BigNumber, string] & {
  index: BigNumber;
  value: string;
};

export interface IImmutableSimulatorInterface extends utils.Interface {
  functions: {
    "getImmutable(address,uint256)": FunctionFragment;
    "setImmutables(address,(uint256,bytes32)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getImmutable" | "setImmutables"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getImmutable",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setImmutables",
    values: [string, ImmutableDataStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getImmutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImmutables",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IImmutableSimulator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IImmutableSimulatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setImmutables(
      _dest: string,
      _immutables: ImmutableDataStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getImmutable(
    _dest: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setImmutables(
    _dest: string,
    _immutables: ImmutableDataStruct[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setImmutables(
      _dest: string,
      _immutables: ImmutableDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setImmutables(
      _dest: string,
      _immutables: ImmutableDataStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setImmutables(
      _dest: string,
      _immutables: ImmutableDataStruct[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
