import { type NextPage } from "next";
import Head from "next/head";
import { Layout } from "../features/Layout";
import Link from "next/link";

const Landing: NextPage = () => {
    const mockData = [
        {
            id: 1,
            title: "Beers",
            description: "We need more beers for the community garden",
            status: "active"
        },
        {
            id: 2,
            title: "Voting 2",
            description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla eget aliquam quam. Donec euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae aliquam nisl nunc eu nisl. Donec euismod, nisl vitae aliquam ultricies, nunc nisl aliquet nunc, vitae aliquam nisl nunc eu nisl.",
            status: "active"
        },
        {
            id: 3,
            title: "Allow Dogs",
            description: "We want to allow dogs in the garden",
            status: "inactive"
        },
        {
            id: 4,
            title: "Ban dogs",
            description: "We dont like dogs in the garden",
            status: "inactive"
        }, {
            id: 5,
            title: "Draft: Water for the garden",
            description: "We are still in draft mode...",
            status: "draft"
        }

    ]
    return (
        <>
            <Head>
                <title>Voting Overview</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                        Vote for Actions for{" "}
                        <span className="text-accent">BCN Poblenou</span>
                    </h1>
                    <div>
                        <Link className="btn btn-secondary" href="/createVoting">Create new Voting</Link>
                    </div>
                    <div className="flex px-4 py-16 w-full">
                        <div className="overflow-x-auto w-full">
                            <table className="table w-full">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Title</th>
                                        <th>Status</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {mockData.map((item) => (
                                        <tr key={item.id}>
                                            <td>{item.id}</td>
                                            <td>{item.title}</td>
                                            <td>{item.status}</td>
                                            <td>
                                                <Link className="btn btn-accent" href={"/voting/" + item.id}>Details</Link>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </Layout>
        </>
    );
};

export default Landing;
