/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../common";

export interface IAccountCodeStorageInterface extends utils.Interface {
  functions: {
    "getCodeHash(uint256)": FunctionFragment;
    "getCodeSize(uint256)": FunctionFragment;
    "getRawCodeHash(address)": FunctionFragment;
    "markAccountCodeHashAsConstructed(address)": FunctionFragment;
    "storeAccountConstructedCodeHash(address,bytes32)": FunctionFragment;
    "storeAccountConstructingCodeHash(address,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getCodeHash"
      | "getCodeSize"
      | "getRawCodeHash"
      | "markAccountCodeHashAsConstructed"
      | "storeAccountConstructedCodeHash"
      | "storeAccountConstructingCodeHash"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCodeHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCodeSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRawCodeHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "markAccountCodeHashAsConstructed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAccountConstructedCodeHash",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAccountConstructingCodeHash",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCodeSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRawCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markAccountCodeHashAsConstructed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAccountConstructedCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAccountConstructingCodeHash",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAccountCodeStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAccountCodeStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getCodeHash(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string] & { codeHash: string }>;

    getCodeSize(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { codeSize: BigNumber }>;

    getRawCodeHash(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string] & { codeHash: string }>;

    markAccountCodeHashAsConstructed(
      _address: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeAccountConstructedCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    storeAccountConstructingCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getCodeHash(_input: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getCodeSize(
    _input: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRawCodeHash(_address: string, overrides?: CallOverrides): Promise<string>;

  markAccountCodeHashAsConstructed(
    _address: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeAccountConstructedCodeHash(
    _address: string,
    _hash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  storeAccountConstructingCodeHash(
    _address: string,
    _hash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getCodeHash(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getCodeSize(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRawCodeHash(
      _address: string,
      overrides?: CallOverrides
    ): Promise<string>;

    markAccountCodeHashAsConstructed(
      _address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    storeAccountConstructedCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    storeAccountConstructingCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getCodeHash(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCodeSize(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRawCodeHash(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    markAccountCodeHashAsConstructed(
      _address: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeAccountConstructedCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    storeAccountConstructingCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCodeHash(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCodeSize(
      _input: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRawCodeHash(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    markAccountCodeHashAsConstructed(
      _address: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeAccountConstructedCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    storeAccountConstructingCodeHash(
      _address: string,
      _hash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
