/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../common";

export interface IPaymasterFlowInterface extends utils.Interface {
  functions: {
    "approvalBased(address,uint256,bytes)": FunctionFragment;
    "general(bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "approvalBased" | "general"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approvalBased",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "general", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "approvalBased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "general", data: BytesLike): Result;

  events: {};
}

export interface IPaymasterFlow extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPaymasterFlowInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    general(
      input: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  approvalBased(
    _token: string,
    _minAllowance: BigNumberish,
    _innerInput: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  general(
    input: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    general(input: BytesLike, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    general(
      input: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approvalBased(
      _token: string,
      _minAllowance: BigNumberish,
      _innerInput: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    general(
      input: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
